name: Scheduled Start Container Instance

on:
  schedule:
    - cron: '*/2 * * * *'  # Setiap 2 menit

permissions:
  id-token: write

jobs:
  start-container:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Start Azure Container Instance
        run: |
          az container start --resource-group RG_DEV --name prediction-risk-register

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Failed to restart container instance `prediction-risk-register`."
          }' https://hooks.slack.com/services/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
