name: Start Container Instance

permissions:
  id-token: write

jobs:
  start-container:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Start Azure Container Instance
        run: |
          az container start --resource-group RG_DEV --name risk-register-predict

      - name: Wait for Container to Start
        run: |
          sleep 10
          az container show --resource-group RG_DEV --name risk-register-predict --query "instanceView.state"

      - name: Get Container Logs
        run: |
          az container logs --resource-group RG_DEV --name risk-register-predict
