name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: monitoringmodel.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Create .env file
        run: |
          echo "# localtoblob" > .env
          echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> .env
          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> .env
          echo "AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}" >> .env
          echo "" >> .env
          echo "# json to db" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "" >> .env
          echo "# data to training model" >> .env
          echo "DB_NAME_MODEL=${{ secrets.DB_NAME_MODEL }}" >> .env
          echo "DB_HOST_MODEL=${{ secrets.DB_HOST_MODEL }}" >> .env
          echo "DB_PORT_MODEL=${{ secrets.DB_PORT_MODEL }}" >> .env
          echo "DB_USER_MODEL=${{ secrets.DB_USER_MODEL }}" >> .env
          echo "DB_PASSWORD_MODEL=${{ secrets.DB_PASSWORD_MODEL }}" >> .env
          echo "" >> .env
          echo "# Slack Webhook" >> .env
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: monitoringmodel.azurecr.io/risk-register-prediction:latest
          build-args: |
            CACHEBUST=$(date +%s)

      - name: Deploy with Docker
        run: |
          docker pull monitoringmodel.azurecr.io/risk-register-prediction:latest
          docker stop risk_predictor || true
          docker rm risk_predictor || true
          docker run -d --name risk_predictor \
            --env-file .env \
            monitoringmodel.azurecr.io/risk-register-prediction:latest
