name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: monitoringmodel.azurecr.io  # Nama ACR Anda
          username: ${{ secrets.AZURE_ACR_USERNAME }}  # Username ACR
          password: ${{ secrets.AZURE_ACR_PASSWORD }}  # Password/token ACR

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: monitoringmodel.azurecr.io/risk_register_predict:latest  # Nama image

      - name: Deploy with Docker
        run: |
          docker pull monitoringmodel.azurecr.io/risk_register_predict:latest
          docker run -d --name risk_predictor monitoringmodel.azurecr.io/risk_register_predict:latest
